import {
	AlertPage,
	AvatarPage,
	BadgePage,
	ButtonPage,
	CardBasicPage,
	CardStatisticPage,
	CheckboxPage,
	ChipPage,
	CollapsiblePage,
	ColorPickerPage,
	Dashboard,
	DatePickerPage,
	DrawerPage,
	ExampleTablePage,
	ExampleTemplateInvoice,
	FileInputPage,
	ListPage,
	MapsPage,
	ModalPage,
	MonthPickerPage,
	PaginationPage,
	PopoverPage,
	RadioPage,
	SelectPage,
	SwitchPage,
	TablePage,
	TabsPage,
	TextAreaPage,
	TextFieldPage,
	TimelinePage,
	TooltipPage,
} from "@/template";
import ExampleTemplateKuitansi from "@/template/Examples/ExampleTemplateKuitansi";
import {
	TbCards,
	TbForms,
	TbId,
	TbMap2,
	TbPerspective,
	TbSmartHome,
	TbTable,
} from "react-icons/tb";

export const menu = [
	{
		icon: <TbSmartHome />,
		path: "/",
		name: "dashboard",
		title: "Dashboard",
		element: <Dashboard />,
		sub: [],
	},
	{
		label: "UI ELEMENTS",
	},
	{
		icon: <TbCards />,
		path: "components",
		name: "components",
		title: "Components",
		element: null,
		sub: [
			{
				icon: null,
				path: "/ui-elements/components/alert",
				name: "alert",
				title: "Alert",
				element: <AlertPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/avatar",
				name: "avatar",
				title: "Avatar",
				element: <AvatarPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/badge",
				name: "badge",
				title: "Badge",
				element: <BadgePage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/button",
				name: "button",
				title: "Button",
				element: <ButtonPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/chip",
				name: "chip",
				title: "Chip",
				element: <ChipPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/collapsible",
				name: "collapsible",
				title: "Collapsible",
				element: <CollapsiblePage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/drawer",
				name: "drawer",
				title: "Drawer",
				element: <DrawerPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/list",
				name: "list",
				title: "List",
				element: <ListPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/modal",
				name: "modal",
				title: "Modal",
				element: <ModalPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/pagination",
				name: "pagination",
				title: "Pagination",
				element: <PaginationPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/popover",
				name: "popover",
				title: "Popover",
				element: <PopoverPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/tabs",
				name: "tabs",
				title: "Tabs",
				element: <TabsPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/tooltip",
				name: "tooltip",
				title: "Tooltip",
				element: <TooltipPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/components/timeline",
				name: "timeline",
				title: "Timeline",
				element: <TimelinePage />,
				sub: [],
			},
		],
	},
	{
		icon: <TbId />,
		path: "cards",
		name: "cards",
		title: "Cards",
		element: null,
		sub: [
			{
				icon: null,
				path: "/ui-elements/cards/basics",
				name: "basics",
				title: "Basics",
				element: <CardBasicPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/ui-elements/cards/statistics",
				name: "statistics",
				title: "Statistics",
				element: <CardStatisticPage />,
				sub: [],
			},
		],
	},
	{
		icon: <TbMap2 />,
		path: "maps",
		name: "maps",
		title: "Maps",
		element: null,
		sub: [
			{
				icon: null,
				path: "/ui-elements/maps/maps",
				name: "maps",
				title: "Maps",
				element: <MapsPage />,
				sub: [],
			},
		],
	},
	{
		label: "FORMS & TABLES",
	},
	{
		icon: <TbForms />,
		path: "forms",
		name: "forms",
		title: "Forms",
		element: null,
		sub: [
			{
				icon: null,
				path: "/form-tables/forms/checkbox",
				name: "checkbox",
				title: "Checkbox",
				element: <CheckboxPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/form-tables/forms/color-picker",
				name: "color-picker",
				title: "Color Picker",
				element: <ColorPickerPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/form-tables/forms/date-picker",
				name: "date-picker",
				title: "Date Picker",
				element: <DatePickerPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/form-tables/forms/file-input",
				name: "file-input",
				title: "File Input",
				element: <FileInputPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/form-tables/forms/month-picker",
				name: "month-picker",
				title: "Month Picker",
				element: <MonthPickerPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/form-tables/forms/radio",
				name: "radio",
				title: "Radio",
				element: <RadioPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/form-tables/forms/select",
				name: "select",
				title: "Select",
				element: <SelectPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/form-tables/forms/switch",
				name: "switch",
				title: "Switch",
				element: <SwitchPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/form-tables/forms/textarea",
				name: "textarea",
				title: "Textarea",
				element: <TextAreaPage />,
				sub: [],
			},
			{
				icon: null,
				path: "/form-tables/forms/textfield",
				name: "textfield",
				title: "Textfield",
				element: <TextFieldPage />,
				sub: [],
			},
		],
	},
	{
		icon: <TbTable />,
		path: "tables",
		name: "tables",
		title: "Tables",
		element: null,
		sub: [
			{
				icon: null,
				path: "/form-tables/tables/table",
				name: "table",
				title: "Table",
				element: <TablePage />,
				sub: [],
			},
		],
	},
	{
		label: "EXAMPLES",
	},
	{
		icon: <TbPerspective />,
		path: "examples",
		name: "examples",
		title: "Examples",
		element: null,
		sub: [
			{
				icon: null,
				path: "/examples/examples/table",
				name: "table",
				title: "Table",
				element: <ExampleTablePage />,
				sub: [],
			},
			{
				icon: null,
				path: "/examples/examples/invoice",
				name: "invoice",
				title: "Invoice",
				element: <ExampleTemplateInvoice />,
				sub: [],
			},
			{
				icon: null,
				path: "/examples/examples/kuitansi",
				name: "kuitansi",
				title: "Kuitansi",
				element: <ExampleTemplateKuitansi />,
				sub: [],
			},
		],
	},
];
